### ISSUE TITLE
Download JSON doesn't work

### ISSUE THREAD

**Issue by penghuo** [opendistro-for-elasticsearch/sql-workbench#53]
## Query
```
SELECT DestCityName, MAX(FlightDelayMin)/COUNT(*)
FROM kibana_sample_data_flights
GROUP BY DestCityName
```

## Issue
Click Download -> Click Download JSON, nothing download.

**Comment by chloe-zh** [comment]
related issue: https://github.com/opendistro-for-elasticsearch/sql/issues/589
