### ISSUE TITLE
Unable to install the plugin for kibana

### ISSUE THREAD

**Issue by H1L021** [opendistro-for-elasticsearch/sql-workbench#70]
Hi @chloe-zh Thank you for your reply
didn't work 
```
root@elk-master:/usr/share/kibana# bin/kibana-plugin install --allow-root file:///home/username/sql-kibana.zip
Attempting to transfer from file:///home/username/sql-kibana.zip
Transferring 56861430 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Plugin installation was unsuccessful due to error "No kibana plugins found in archive"
```

_Originally posted by @H1L021 in https://github.com/opendistro-for-elasticsearch/sql-kibana-plugin/issues/69#issuecomment-629763166_

**Comment by rosslutsch** [comment]
got the same issue, could you solve it?

**Comment by anirudha** [comment]
are you trying this on opendistro kibana to connect to opendistro ES?

**Comment by rosslutsch** [comment]
yes it is, I unzipped it and changed the directory setup, it then "installs" but then the container doesn't start

**Comment by chloe-zh** [comment]
Could you try ./kibana-plugin install `plugin-name` --batch, it should work. And if you have any further issue with it, please turn to our main repository [ODFE-SQL](https://github.com/opendistro-for-elasticsearch/sql) to create issues since this sql workbench repository is deprecated. Thanks!
