### ISSUE TITLE
does sql-workbench support x-pack sql?

### ISSUE THREAD

**Issue by yoke88** [opendistro-for-elasticsearch/sql-workbench#76]
the readme does not shown whether sql-workbench support x-pack sql, so i submit an issue here. because the endpoint is different from x-pack sql and opendistro sql plugin , but i think it is better to support both , and we can choose the sql endpoint.

**Comment by chloe-zh** [comment]
The workbench doesn’t support xpack for now. Thanks for your suggestion and we will consider it.

**Comment by yoke88** [comment]
and there is no doc for sql-workbench here

`https://opendistro.github.io/for-elasticsearch-docs/docs/kibana/plugins/`

**Comment by anirudha** [comment]
https://opendistro.github.io/for-elasticsearch-docs/docs/sql/workbench/
the docs are here.

please reopen if you need more information
