### ISSUE TITLE
Can't display some field columns

### ISSUE THREAD

**Issue by joshuali925** [opendistro-for-elasticsearch/sql-workbench#83]
![image](https://user-images.githubusercontent.com/28062824/86392681-b8ad6b80-bc50-11ea-8b25-423007ab79b7.png)
There should be `geo`, `machine`, `event` columns after the `response` column in `kibana_sample_data_logs`, but they are not showing up for query `select * from kibana_sample_data_logs`.

**Comment by chloe-zh** [comment]
Geo is because we didn’t set proper JDBC type for geo type. But for others, is the behavior inconsistent with sql plugin?

**Comment by joshuali925** [comment]
> Geo is because we didn’t set proper JDBC type for geo type. But for others, is the behavior inconsistent with sql plugin?

The table is using aliases in JDBC response as column names even if aliases are empty, I submitted a pr that fixes this.
